### ISSUE TITLE
[Bug] Grover Benchmarks errors

### ISSUE THREAD

**Issue by isolatedinformation** [latticesurgery-com/liblsqecc#28] opened 2022-10-14 09:52 UTC
in the branch [`grover-benchmarks`](https://github.com/latticesurgery-com/benchmark/tree/grover-benchmarks) in the `benchmark` repo the lsi files for grovers can be found at `grover/grover_lsi`

The slicer runs succesfully for `lsqecc_slicer -i grover/grover_lsi/grover_3.txt -f progress -o grover/grover_lsi/grover_3.json`. For other combinations errors are thrown, (listed below here).

1. Compact Layout not working
```bash
$ lsqecc_slicer -i grover/grover_lsi/grover_3.txt -f progress --compactlayout --graceful
Encountered exception: Couldn't find room to route: 0:Z,5:Z
Halting slicing
LS Instructions read  22
Slices 15
Made patch computation. Took 0.000811253s.
```

2. For >=5 qubits, lsqecc_slicer fails in simple layout
```bash
$ lsqecc_slicer -i grover/grover_lsi/grover_5.txt -f progress
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 8) >= this->size() (which is 8)
Aborted
```
3. . For >=5 qubits, lsqecc_slicer fails in compact layout or custom layout
```bash
../liblsqecc/cmake-build-debug/lsqecc_slicer -i grover/grover_lsi/grover_5.txt -f progress --compactlayout
terminate called after throwing an instance of 'std::runtime_error'
  what():  Could not get magic state after waiting
Aborted
```

**Comment by gwwatkin** [comment] 2022-10-16 21:17
Thanks for pointing these out. Looks like there are some more cases to handle. Currently developing a test suite. Will address these and add them as test cases.

Can you post the layout files?

**Comment by isolatedinformation** [comment] 2022-10-16 22:37
[`grovers-benchmark`](https://github.com/latticesurgery-com/benchmark/tree/grover-benchmarks?rgh-link-date=2022-10-14T09%3A52%3A36Z) branch has the layout files at `grover/grover_layout.txt` and `grover/dummy_layout.txt`

**Comment by gwwatkin** [comment] 2022-10-21 04:20
Points 1 and 3 will be addressed by the next CR

As for point 2. The problem is that the simple layout only supports a fixed number of qubits.

 * Tracked the issue here #31 

For now please use `--compactlayout`

**Closed** 2022-10-23 23:33 UTC
